//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Albums struct {
	ID          int32
	ArtistID    *int32
	AlbumName   *string
	Genre       *string
	ReleaseYear *int32
	ReissueYear *int32
	Label       *int32
	Coloured    *bool
	Cover       *string
}
