version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: tgbot-db-postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./bot.sql:/docker-entrypoint-initdb.d/bot.sql
