// Code generated by SQLBoiler 4.9.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAlbums(t *testing.T) {
	t.Parallel()

	query := Albums()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAlbumsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAlbumsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Albums().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAlbumsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AlbumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAlbumsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AlbumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Album exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AlbumExists to return true, but got false.")
	}
}

func testAlbumsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	albumFound, err := FindAlbum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if albumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAlbumsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Albums().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAlbumsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Albums().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAlbumsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	albumOne := &Album{}
	albumTwo := &Album{}
	if err = randomize.Struct(seed, albumOne, albumDBTypes, false, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}
	if err = randomize.Struct(seed, albumTwo, albumDBTypes, false, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = albumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = albumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Albums().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAlbumsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	albumOne := &Album{}
	albumTwo := &Album{}
	if err = randomize.Struct(seed, albumOne, albumDBTypes, false, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}
	if err = randomize.Struct(seed, albumTwo, albumDBTypes, false, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = albumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = albumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func albumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func albumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Album) error {
	*o = Album{}
	return nil
}

func testAlbumsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Album{}
	o := &Album{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, albumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Album object: %s", err)
	}

	AddAlbumHook(boil.BeforeInsertHook, albumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	albumBeforeInsertHooks = []AlbumHook{}

	AddAlbumHook(boil.AfterInsertHook, albumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	albumAfterInsertHooks = []AlbumHook{}

	AddAlbumHook(boil.AfterSelectHook, albumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	albumAfterSelectHooks = []AlbumHook{}

	AddAlbumHook(boil.BeforeUpdateHook, albumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	albumBeforeUpdateHooks = []AlbumHook{}

	AddAlbumHook(boil.AfterUpdateHook, albumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	albumAfterUpdateHooks = []AlbumHook{}

	AddAlbumHook(boil.BeforeDeleteHook, albumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	albumBeforeDeleteHooks = []AlbumHook{}

	AddAlbumHook(boil.AfterDeleteHook, albumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	albumAfterDeleteHooks = []AlbumHook{}

	AddAlbumHook(boil.BeforeUpsertHook, albumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	albumBeforeUpsertHooks = []AlbumHook{}

	AddAlbumHook(boil.AfterUpsertHook, albumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	albumAfterUpsertHooks = []AlbumHook{}
}

func testAlbumsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAlbumsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(albumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAlbumToManyCollections(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c Collection

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, collectionDBTypes, false, collectionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, collectionDBTypes, false, collectionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.AlbumID, a.ID)
	queries.Assign(&c.AlbumID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Collections().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.AlbumID, b.AlbumID) {
			bFound = true
		}
		if queries.Equal(v.AlbumID, c.AlbumID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := AlbumSlice{&a}
	if err = a.L.LoadCollections(ctx, tx, false, (*[]*Album)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Collections); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Collections = nil
	if err = a.L.LoadCollections(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Collections); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testAlbumToManyWishlists(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c Wishlist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, wishlistDBTypes, false, wishlistColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, wishlistDBTypes, false, wishlistColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.AlbumID, a.ID)
	queries.Assign(&c.AlbumID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Wishlists().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.AlbumID, b.AlbumID) {
			bFound = true
		}
		if queries.Equal(v.AlbumID, c.AlbumID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := AlbumSlice{&a}
	if err = a.L.LoadWishlists(ctx, tx, false, (*[]*Album)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Wishlists); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Wishlists = nil
	if err = a.L.LoadWishlists(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Wishlists); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testAlbumToManyAddOpCollections(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c, d, e Collection

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Collection{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, collectionDBTypes, false, strmangle.SetComplement(collectionPrimaryKeyColumns, collectionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Collection{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCollections(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.AlbumID) {
			t.Error("foreign key was wrong value", a.ID, first.AlbumID)
		}
		if !queries.Equal(a.ID, second.AlbumID) {
			t.Error("foreign key was wrong value", a.ID, second.AlbumID)
		}

		if first.R.Album != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Album != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Collections[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Collections[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Collections().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testAlbumToManySetOpCollections(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c, d, e Collection

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Collection{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, collectionDBTypes, false, strmangle.SetComplement(collectionPrimaryKeyColumns, collectionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetCollections(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Collections().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetCollections(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Collections().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.AlbumID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.AlbumID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.AlbumID) {
		t.Error("foreign key was wrong value", a.ID, d.AlbumID)
	}
	if !queries.Equal(a.ID, e.AlbumID) {
		t.Error("foreign key was wrong value", a.ID, e.AlbumID)
	}

	if b.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Album != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Album != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Collections[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Collections[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testAlbumToManyRemoveOpCollections(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c, d, e Collection

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Collection{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, collectionDBTypes, false, strmangle.SetComplement(collectionPrimaryKeyColumns, collectionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddCollections(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Collections().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveCollections(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Collections().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.AlbumID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.AlbumID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Album != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Album != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Collections) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Collections[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Collections[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testAlbumToManyAddOpWishlists(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c, d, e Wishlist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Wishlist{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Wishlist{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWishlists(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.AlbumID) {
			t.Error("foreign key was wrong value", a.ID, first.AlbumID)
		}
		if !queries.Equal(a.ID, second.AlbumID) {
			t.Error("foreign key was wrong value", a.ID, second.AlbumID)
		}

		if first.R.Album != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Album != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Wishlists[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Wishlists[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Wishlists().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testAlbumToManySetOpWishlists(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c, d, e Wishlist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Wishlist{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetWishlists(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Wishlists().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetWishlists(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Wishlists().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.AlbumID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.AlbumID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.AlbumID) {
		t.Error("foreign key was wrong value", a.ID, d.AlbumID)
	}
	if !queries.Equal(a.ID, e.AlbumID) {
		t.Error("foreign key was wrong value", a.ID, e.AlbumID)
	}

	if b.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Album != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Album != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Wishlists[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Wishlists[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testAlbumToManyRemoveOpWishlists(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c, d, e Wishlist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Wishlist{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddWishlists(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Wishlists().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveWishlists(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Wishlists().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.AlbumID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.AlbumID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Album != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Album != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Album != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Wishlists) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Wishlists[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Wishlists[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testAlbumToOneArtistUsingArtist(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Album
	var foreign Artist

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, artistDBTypes, false, artistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Artist struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ArtistID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Artist().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := AlbumSlice{&local}
	if err = local.L.LoadArtist(ctx, tx, false, (*[]*Album)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Artist == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Artist = nil
	if err = local.L.LoadArtist(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Artist == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testAlbumToOneSetOpArtistUsingArtist(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b, c Artist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, artistDBTypes, false, strmangle.SetComplement(artistPrimaryKeyColumns, artistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, artistDBTypes, false, strmangle.SetComplement(artistPrimaryKeyColumns, artistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Artist{&b, &c} {
		err = a.SetArtist(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Artist != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Albums[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ArtistID, x.ID) {
			t.Error("foreign key was wrong value", a.ArtistID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ArtistID))
		reflect.Indirect(reflect.ValueOf(&a.ArtistID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ArtistID, x.ID) {
			t.Error("foreign key was wrong value", a.ArtistID, x.ID)
		}
	}
}

func testAlbumToOneRemoveOpArtistUsingArtist(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Album
	var b Artist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, albumDBTypes, false, strmangle.SetComplement(albumPrimaryKeyColumns, albumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, artistDBTypes, false, strmangle.SetComplement(artistPrimaryKeyColumns, artistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetArtist(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveArtist(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Artist().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Artist != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ArtistID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Albums) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAlbumsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAlbumsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AlbumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAlbumsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Albums().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	albumDBTypes = map[string]string{`ID`: `integer`, `ArtistID`: `integer`, `AlbumName`: `character varying`, `Genre`: `character varying`, `ReleaseYear`: `integer`, `ReissueYear`: `integer`, `Label`: `character varying`, `Coloured`: `boolean`, `CoverID`: `character varying`}
	_            = bytes.MinRead
)

func testAlbumsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(albumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(albumAllColumns) == len(albumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, albumDBTypes, true, albumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAlbumsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(albumAllColumns) == len(albumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Album{}
	if err = randomize.Struct(seed, o, albumDBTypes, true, albumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, albumDBTypes, true, albumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(albumAllColumns, albumPrimaryKeyColumns) {
		fields = albumAllColumns
	} else {
		fields = strmangle.SetComplement(
			albumAllColumns,
			albumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AlbumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAlbumsUpsert(t *testing.T) {
	t.Parallel()

	if len(albumAllColumns) == len(albumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Album{}
	if err = randomize.Struct(seed, &o, albumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Album: %s", err)
	}

	count, err := Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, albumDBTypes, false, albumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Album struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Album: %s", err)
	}

	count, err = Albums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
