// Code generated by SQLBoiler 4.9.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Albums     string
	Artists    string
	Collection string
	Info       string
	Locations  string
	Users      string
}{
	Albums:     "albums",
	Artists:    "artists",
	Collection: "collection",
	Info:       "info",
	Locations:  "locations",
	Users:      "users",
}
