// Code generated by SQLBoiler 4.9.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Albums", testAlbumsUpsert)

	t.Run("Artists", testArtistsUpsert)

	t.Run("Collections", testCollectionsUpsert)

	t.Run("Infos", testInfosUpsert)

	t.Run("Locations", testLocationsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("Wishlists", testWishlistsUpsert)
}
